var oldText;(function($){$(window).load(function(){var reloadButton=$(".inventory_refresh_button");oldText=reloadButton.val();reloadButton.click(function(){$(".inventory_refresh_button").css("font-family","'Titillium Web', sans-serif");reloadButton.attr('value','Loading...');doSend('invreload');});$(".item_search_input").keyup(displayItems);$(".inventory_deposit").click(depositItems);$(".inventory_withdraw").click(onWithdraw);var inventorySelectors=$(".inventory_tab");inventorySelectors.click(function(e){var tab=e.currentTarget;if(tab.id==="inventory_tab_virtual"){$(".inventory_withdraw").show();$(".inventory_items").css({"bottom":"103px"});$(".inventory_deposit_area").css({"height":"100px"});$(".inventory_deposit").css({"height":"65%"});}else{$(".inventory_withdraw").hide();$(".inventory_items").css({"bottom":"64px"});$(".inventory_deposit_area").css({"height":"64px"});$(".inventory_deposit").css({"height":"100%"});}
inventorySelectors.removeClass('inventory_tab_selected');inventorySelectors.addClass('inventory_tab_deselected');tab.className='inventory_tab inventory_tab_selected';$(".selected_item").removeClass("selected_item");displayItems();});});})(jQuery);function getInventoryItemDivText(item){var backGroundIMGURL="http://gamblecsgo.com/asset?name=img/item_bg.png";var itemURL="http://cdn.steamcommunity.com/economy/image/"+ item.icon_url;var price=Number(item.price/100).toFixed(2);var htmlValue="<div id=\""+ item.id+"\" class=\"inventory_item "+ item.clazz+"\" original-title=\""+ item.name+" "+ item.quality+"\">";if(item.isVirtual){htmlValue+="<div class='virtual_item'></div>";}
htmlValue+="<div id=\"item_overlay_"+ item.id+"\"\ data-is-virtual=\""+ item.isVirtual+"\"></div>"+"<img class='inventory_item_bg' src="+ backGroundIMGURL+">"+"<div class='inventory_item_weapon_holder'><img src='"+ itemURL+"' class='inventory_item_weapon'></div>"+"<p class='inventory_item_p_line'>$"+ price+"</p>"+"</div>";return htmlValue;}
function getInventoryItemDiv(item){var itemDiv=$(getInventoryItemDivText(item));return itemDiv;}
function deselectAll(){$(".selected_item").fadeOut(125).toggleClass("selected_item");$(".inventory_deposit").prop("disabled",false);recalculateTotal();}
function addInventoryItemListeners(item){var itemDiv=item.itemDiv;itemDiv.bind('mousedown',function(){var overlay=$('#item_overlay_'+ item.id);var wasSelected=overlay.hasClass("selected_item");if(wasSelected){overlay.fadeOut(125);setTimeout(function(){if($(".inventory_tab_selected").attr("id")==="inventory_tab_both"&&overlay.data("is-virtual")&&getSelectedItemCount()>=10){return;}
overlay.toggleClass("selected_item");if(getSelectedVirtualItemCount()>10){$(".inventory_deposit").prop("disabled",true);$(".inventory_deposit").attr("value","Max 10 items per deposit into the pot");}else{$(".inventory_deposit").prop("disabled",false);recalculateTotal();}},125);}else{if(getSelectedVirtualItemCount()>=10){$(".inventory_deposit").prop("disabled",true);$(".inventory_deposit").attr("value","Max 10 items per deposit into the pot");overlay.toggleClass("selected_item");overlay.fadeIn(125);return;}else{overlay.toggleClass("selected_item");overlay.fadeIn(125);$(".inventory_deposit").prop("disabled",false);}}
recalculateTotal();});itemDiv.data('item',item);itemDiv.tipsy({gravity:'w'});}
function recalculateTotal(){var total=0;var itemsContainer=$(".inventory_items_container");itemsContainer.children().each(function(){var child=$(this);if($('#item_overlay_'+ child.attr('id')).hasClass("selected_item")){var item=child.data('item');total+=item.price;}});var totalPrice=Number(total/100).toFixed(2);$('.inventory_deposit').val('Deposit\n($'+ totalPrice+')');}
var items;function updateInventoryIds(oldIdsToNewIds){for(var i=0;i<oldIdsToNewIds.length;i++){var oldToNew=oldIdsToNewIds[i];for(var x=0;x<items.length;x++){var item=items[x];if(item.id==oldToNew.itemId){item.id=oldToNew.virtualItemId;item.isVirtual=true;item.itemDiv=getInventoryItemDiv(item);}}}
displayItems();}
function loadInventory(jsonItems){$(".tipsy").hide();items=JSON.parse(jsonItems).items;items.sort(function(a,b){var priceDiff=b.price- a.price;if(priceDiff==0){var nameA=a.name.toLowerCase();var nameB=b.name.toLowerCase();if(nameA<nameB){return-1;}
if(nameA>nameB){return 1;}
return 0;}
return priceDiff;});for(var i=0;i<items.length;i++){var item=items[i];item.itemDiv=getInventoryItemDiv(item);}
var itemsContainer=$(".inventory_items_container");itemsContainer.empty();displayItems();$(".tipsy").hide();}
function displayItems(){if(items==null){return;}
var itemsContainer=$(".inventory_items_container");itemsContainer.empty();var searchText=$(".item_search_input").val().toLowerCase();var tab=$('.inventory_tab_selected').prop('id');for(var i=0;i<items.length;i++){var item=items[i];if(shouldDisplay(item,searchText,tab)){addInventoryItemListeners(item);item.itemDiv.appendTo(itemsContainer);}}
var refreshButton=$(".inventory_refresh_button");refreshButton.css("font-family","'Glyphicons Halflings'");refreshButton.val(oldText);refreshButton.blur();if(items.length===0){$('#inventory-items').block({css:{width:'60%',border:'0px solid #FFFFFF',cursor:'wait',backgroundColor:'#D8DCDG',opacity:1.0},overlayCSS:{backgroundColor:'#FFFFFF',opacity:0.0,cursor:'wait'},message:'<p>You don\'t have any items in your inventory.</p>'});}else{$('#inventory-items').unblock();}}
function shouldDisplay(item,searchText,currentTab){var totalName=(item.name+" "+ item.quality).toLowerCase();if(item.isVirtual&&currentTab=='inventory_tab_steam'||!item.isVirtual&&currentTab=='inventory_tab_virtual'){return false;}
return totalName.contains(searchText);}
function getSelectedVirtualItemCount(){var counter=0;var itemsContainer=$(".inventory_items_container");itemsContainer.children().each(function(){var child=$(this);var overlay=$('#item_overlay_'+ child.attr('id'));if(overlay.hasClass("selected_item")&&overlay.data("is-virtual")){counter++;}});return counter;}
function getSelectedItemCount(){var counter=0;var itemsContainer=$(".inventory_items_container");itemsContainer.children().each(function(){var child=$(this);var overlay=$('#item_overlay_'+ child.attr('id'));if(overlay.hasClass("selected_item")){counter++;}});return counter;}
function removeFromInventory(itemIdsToRemove){var newItems=[];for(var x=0;x<items.length;x++){var item=items[x];for(var i=0;i<itemIdsToRemove.length;i++){var idToRemove=parseInt(itemIdsToRemove[i].trim());if(item.id==idToRemove){items.splice(x,1);x--;break;}}}
displayItems();}
function depositItems(){var items=[];var itemsContainer=$(".inventory_items_container");itemsContainer.children().each(function(){var child=$(this);if($('#item_overlay_'+ child.attr('id')).hasClass("selected_item")){var item=child.data('item');items.push(item.id+':'+ item.isVirtual);}});if(items.length==0){return;}
doSend('deposit'+ JSON.stringify(items));openTradeConfirmPopup();}
function onWithdraw(){var items=[];var itemsContainer=$(".inventory_items_container");itemsContainer.children().each(function(){var child=$(this);if($('#item_overlay_'+ child.attr('id')).hasClass("selected_item")){var item=child.data('item');items.push(item.id+':'+ item.isVirtual);}});if(items.length==0){return;}
doSend('withdraw'+ JSON.stringify(items));openWithdrawalsPopup();}