var plusIMGURL="http://gamblecsgo.com/asset?name=img/plus.png";var minusIMGURL="http://gamblecsgo.com/asset?name=img/minus.png";(function($){$(window).load(function(){$("#container_items").mCustomScrollbar({scrollInertia:400,autoHideScrollbar:true,axis:"x",theme:"dark-thin",autoExpandScrollbar:true,scrollButtons:{enable:true},advanced:{autoExpandHorizontalScroll:true,updateOnBrowserResize:true,updateOnContentResize:true}});if(typeof localSteamID==='undefined'){$('#inventory-items').block({css:{width:'60%',border:'0px solid #FFFFFF',cursor:'pointer',backgroundColor:'#D8DCDG',opacity:1.0},overlayCSS:{backgroundColor:'#FFFFFF',opacity:0.0,cursor:'pointer'},message:'<p>You need to be logged in to see your inventory.</p>'});$('#inventory-items').find('.blockOverlay').click(function(){openPopup('loginPopup');});}});})(jQuery);var maxPotItems=0;var potItems=0;function updatePotItemCount(delta){potItems+=delta;$("#statistics_pot_items").html(potItems+"/"+ maxPotItems);var percent=Math.min(100,potItems/maxPotItems*100);$(".pot_status_progress").stop();$(".pot_status_progress").animate({width:percent+"%"},500,'easeOutBounce');}
function newGame(maxItems,hash){maxPotItems=maxItems;addLogEntry("newgame",hash);var winnerPicker=$(".winner_picker");$("#jackpot_items_list").empty();$("#container_items").mCustomScrollbar("update");if(winnerPicker.is(":visible")){winnerPicker.fadeOut(500);setTimeout(resetPot,500);}else{resetPot();}}
function resetPot(){document.title="$0.00 - "+$("#title").val();updatePotItemCount(-potItems);$(".pot_status_text").text("$0.00");$("#your-deposit-stats").text("$0.00");$("#your-odds-stats").text("0%");$("#container_items").fadeIn(50);$(".pot_status_timer").stop();$(".pot_status_timer").width(0);}
function startTimer(seconds){$(".pot_status_timer").stop();$(".pot_status_timer").width(0);$(".pot_status_timer").animate({width:"100%"},seconds*1000,'linear');}
function toggle(elementId){var toggleIcon=$("#toggle-"+ elementId);var next=$("#log_block_expand_content_"+ elementId);if(next.is(":visible")){next.fadeOut(100);toggleIcon.prop("src",plusIMGURL);}else{next.fadeIn(300);toggleIcon.prop("src",minusIMGURL);}}
function addLogEntry(entryType,obj){var hash=Hashcode.value(JSON.stringify(obj));var maxSize=$("#log-items").attr("data");var count=$('.log_block').length;if(count>=maxSize){$(".log_block:last-child").remove();}
var html='<div class="log_block" id="log_'+ hash+'">';var profileURL;switch(entryType){case'newgame':html+='<div class="log_block_round_start">';html+='<b>Round hash: <span style="color: white">'+ obj+'</span></b>';html+='</div>';break;case'winner':var name=obj.winner.name;if(name.toLowerCase().indexOf("gamblecsgo")===-1){name=name.replace(".net","").replace(".com","").replace(".org","").replace(".info","").replace(".me","").replace(".NET","").replace(".COM","").replace(".ORG","").replace(".Info","").replace(".Me","").replace(".Net","").replace(".Com","").replace(".Org","").replace(".Info","").replace(".Me","");}
profileURL="http://steamcommunity.com/profiles/"+ obj.winner.id;var winnerHtml="";winnerHtml+='<div class="log_block_winner">';winnerHtml+='<a class="log_block_avatar"'+(obj.showProfileLink?('href="'+ profileURL+'" target = "_blank"'):(''))+'><img style="height:100%" src="'
+ obj.winner.avatarURL+'" border="0"></a><a style="display:inline-block" class="log_block_depositer" '+
(obj.showProfileLink?('href="'+ profileURL+'" target = "_blank"'):(''))
+'>'+ name+'</a>'+'<b><span style="color: #4B667B; display:inline-block">&nbsp;won the pot worth $'+ Number(obj.totalValue/100).toFixed(2)
+'</span></b>&nbsp;<a id="log_block_expand_'+ hash+'" class="log_block_expand"><img id="toggle-'+ hash+'" src="'+ plusIMGURL+'" /></a>';winnerHtml+='<div id="log_block_expand_content_'+ hash+'" class="log_items_images" style="line-height: 16px">';winnerHtml+='<b style="font-size: 16px;">';winnerHtml+='Chance of winning: '+ Number(obj.chance).toFixed(2)+'%';winnerHtml+='<br>';winnerHtml+='Secret: '+ obj.secret;winnerHtml+='<br>';winnerHtml+='Winning ticket found at percentage: '+ obj.winPercentage+'%';winnerHtml+='</b>';winnerHtml+='</div></div>';html+=winnerHtml;break;case'bet':var totalValue=0;for(var i=0;i<obj.items.length;i++){var item=obj.items[i];totalValue+=item.price;}
var betHtml="";var name=obj.better.name;if(name.toLowerCase().indexOf("gamblecsgo")===-1){name=name.replace(".net","").replace(".com","").replace(".org","").replace(".info","").replace(".me","").replace(".NET","").replace(".COM","").replace(".ORG","").replace(".Info","").replace(".Me","").replace(".Net","").replace(".Com","").replace(".Org","").replace(".Info","").replace(".Me","");}
profileURL="http://steamcommunity.com/profiles/"+ obj.better.id;var backGroundIMGURL="http://gamblecsgo.com/asset?name=img/item_bg.png";betHtml+='<div class="log_block_second_line">';betHtml+='<a class="log_block_avatar"'+(obj.showProfileLink?('href="'+ profileURL+'" target = "_blank"'):(''))+'><img style="height:100%" src="'
+ obj.better.avatarURL+'" border="0"></a><a style="display:inline-block" class="log_block_depositer" '+
(obj.showProfileLink?('href="'+ profileURL+'" target = "_blank"'):(''))+'>'+ name+'</a>'+'<b><span style="color: #4B667B; display:inline-block">&nbsp;deposited '+ obj.items.length+' items worth $'+ Number(totalValue/100).toFixed(2)
+'</span></b>&nbsp;<a id="log_block_expand_'+ hash+'" class="log_block_expand"><img id="toggle-'+ hash+'" src="'+ plusIMGURL+'" /></a>';betHtml+='<div id="log_block_expand_content_'+ hash+'" class="log_items_images">';betHtml+='<ul>';for(var i=0;i<obj.items.length;i++){betHtml+='<li style="display: inline-block">';var item=obj.items[i];var itemURL="http://cdn.steamcommunity.com/economy/image/"+ item.icon_url;var price=Number(item.price/100).toFixed(2);var htmlValue="<div id=\"item_"+ hash+"_"+ i+"\" class=\"inventory_item "+ item.clazz+"\" style=\"position: relative; float: none;\" original-title=\""+ item.name+" "+ item.quality+"\">"+"<div id=\"item_overlay_"+ item.id+"\"\></div>"+"<img class='inventory_item_bg' style='left: 0' src="+ backGroundIMGURL+">"+"<div class='inventory_item_weapon_holder'><img src='"+ itemURL+"' class='inventory_item_weapon'></div>"+"<p class='inventory_item_p_line'>$"+ price+"</p>"+"</div>";betHtml+=htmlValue;betHtml+='</li>';}
betHtml+='</ul>';betHtml+='</div></div>';html+=betHtml;break;}
html+='</div></div>';$('.log_items_container').prepend(html);if(entryType=="bet"){for(var i=0;i<obj.items.length;i++){$("#item_"+ hash+"_"+ i).tipsy({gravity:'w'});}
$("#log_block_expand_"+ hash).click(function(){toggle(hash);});}else if(entryType=="winner"){$("#log_block_expand_"+ hash).click(function(){var currentCursor=$(this).css('cursor');toggle(hash);});}}
function addBet(bet){var totalValue=0;for(var i=0;i<bet.items.length;i++){var item=bet.items[i];addBetItem(item);totalValue+=item.price;}
bet.totalValue=totalValue;addLogEntry('bet',bet);var currentPot=Number(Number($(".pot_status_text").text().trim().substr(1))*100);var newPot=Number((Number(currentPot)+ Number(totalValue))/ 100).toFixed(2);
$(".pot_status_text").text(("$"+ newPot));document.title="$"+ newPot+" pot! - "+$("#title").val();if(typeof localSteamID!='undefined'&&bet.better.id==localSteamID){closePopups();var currentDeposit=Number(Number($("#your-deposit-stats").text().trim().substr(1)))*100;var newDeposit=Number((currentDeposit+ totalValue)/ 100).toFixed(2);
$("#your-deposit-stats").text(("$"+ newDeposit));}
var localDeposit=Number(Number($("#your-deposit-stats").text().trim().substr(1)));var odds=Number(localDeposit/newPot*100).toFixed(2);$("#your-odds-stats").text(odds+"%");}
function addBetItem(item){updatePotItemCount(1);var backGroundIMGURL="http://gamblecsgo.com/asset?name=img/item_bg.png";var itemURL="http://cdn.steamcommunity.com/economy/image/"+ item.icon_url;var price=Number(item.price/100).toFixed(2);var name=item.name;var quality=item.quality;if(name.contains("Weapon Case")){name=name.replace("Weapon Case","");quality="Weapon Case";}
if(quality==""){quality="<br>";}
var htmlValue="<li class='sh'>"+"<div id=\"container_items_item\" class=\""+ item.clazz+"\">"+"<img class=\"item_bg\" src="+ backGroundIMGURL+"/>"+"<div class='pot_item_weapon_holder'><img src="+ itemURL+" class=\"items_weapon\"/></div>"+"<p class=\"item_f_line\">"+ name+"</p>"+"<p class=\"item_s_line\">"+ quality+"</p>"+"<div class=\"seperator\"></div>"+"<p class=\"item_p_line\">$"+ price+"</p>"+"</div>"+"</li>";var jqueryItem=$(htmlValue);jqueryItem.data('item',item);var jackpotItemsList=$("#jackpot_items_list");if(jackpotItemsList.children().length==0){jqueryItem.hide().appendTo("#jackpot_items_list").fadeIn(500);}else{var added=false;jackpotItemsList.children().each(function(){var child=$(this);var itemPrice=child.data('item').price;if(item.price>itemPrice){added=true;jqueryItem.hide().insertBefore(child).fadeIn(500);return false;}});if(!added){jqueryItem.hide().appendTo("#jackpot_items_list").fadeIn(500);}}
$("#container_items").mCustomScrollbar("update");}
function pickWinner(winner,betters){random=Math.seed(winner.value);$("#container_items").fadeOut(500);$(".winner_picker_betters_list").empty();setTimeout(function(){var winnerIndex=Math.floor(15+ random()*10);seed=25;var jqueryItem;var htmlBlock;for(var i=0;i<winnerIndex;i++){var randomBetter=getRandomBetter(betters);htmlBlock=createBetterCard(randomBetter);jqueryItem=$(htmlBlock);jqueryItem.hide().appendTo(".winner_picker_betters_list").fadeIn(500);}
htmlBlock=createBetterCard(winner);jqueryItem=$(htmlBlock);jqueryItem.hide().appendTo(".winner_picker_betters_list").fadeIn(500);for(var i=0;i<winnerIndex;i++){var randomBetter=getRandomBetter(betters);htmlBlock=createBetterCard(randomBetter);jqueryItem=$(htmlBlock);jqueryItem.hide().appendTo(".winner_picker_betters_list").fadeIn(500);}
$(".winner_picker").fadeIn(50);var xLocation=(jqueryItem.width()*winnerIndex);var randomizedFactor=(random()- 0.5)*0.8;var randomizedX=jqueryItem.width()*randomizedFactor;$(".winner_picker_betters_list").css({'left':xLocation});var containerWidth=$(".winner_picker").width();var easingFunction=function(x,t,b,c,d){return c*((t=t/d- 1)*t*t*t*t+ 1)+ b;};$(".winner_picker_betters_list").animate({'left':randomizedX},8000,"easeOutQuint");timeLeft=8000;setTimeout(checkPlaySound,30);},500);}
var lastPlayedIndex=0;var itemScroll;itemScroll=new Audio();itemScroll.src="http://gamblecsgo.com/asset?name=sound/crate_scroll.wav";itemScroll.volume=0.2;var timeLeft;function checkPlaySound(){var left=$(".winner_picker_betters_list").position().left;var index=Math.ceil((left/134)- 0.5);if(lastPlayedIndex!=index){itemScroll.pause();itemScroll.currentTime=0;itemScroll.play();lastPlayedIndex=index;}
timeLeft-=30;if(timeLeft>0){setTimeout(checkPlaySound,30);}}
function createBetterCard(better){var htmlBlock="<li>"+"<div id='container_items_item' class='items_gray'>"+"<img class=\"winner_picker_better_avatar\" src="+ better.better.avatarFullURL+"/>"+"<p class=\"winner_picker_better_name\">"+ better.better.name+"</p>"+"</div>"+"</li>";return htmlBlock;}
function getRandomBetter(betters){var totalTickets=0;var allBettersTickets=[];for(var i=0;i<betters.length;i++){var better=betters[i];var bettersTickets=better.value;allBettersTickets[i]=bettersTickets;totalTickets+=bettersTickets;}
var currentTicketTotal=0;var winningTicket=Math.floor(random()*totalTickets);for(var i=0;i<betters.length;i++){currentTicketTotal+=allBettersTickets[i];if(winningTicket<currentTicketTotal){return betters[i];}}
return betters[Math.floor(random()*betters.length)];}
Math.seed=function(s){return function(){s=Math.sin(s)*10000;return s- Math.floor(s);};};var random;