function setCookie(cname,cvalue,exdays){var d=new Date();d.setTime(d.getTime()+(exdays*24*60*60*1000));var expires="expires="+d.toUTCString();document.cookie=cname+"="+ cvalue+"; "+ expires;}
var hostname="http://"+ location.hostname+(location.port?":"+ location.port:"");var assetPath="/asset?name=";function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return"";}
var pvSpinner;$(window).load(function(){emojify.setConfig({img_dir:hostname+ assetPath+"img/emoji"});String.prototype.contains=function(it){return this.indexOf(it)!=-1;};$(document).on("click",".retry-withdraw-btn",function(event){var target=$(event.target);onWithdrawRetry(target.data("withdrawId"));target.attr('value','Sending...');target.attr('disabled',true);});Tipped.create('#login-why','We need you to login so that we can trade items with you!');var tradeURLInput=$("#trade_url_input");var defaultValue=tradeURLInput.val().trim();tradeURLInput.data("lastval",defaultValue);var checkInput=function(){var input=tradeURLInput.val().trim();if(tradeURLInput.data("lastval")!=input){if(input.contains("token")){var token=input.substring(input.indexOf("token=")+ 6);if(token.length==8){doSend("trade_url"+ input);tradeURLInput.prop('disabled',true);}}}};$('#link_profile_checkbox').change(function(){var checked=$(this).is(":checked");doSend("show_profile_link"+ checked);});tradeURLInput.on('input propertychange',checkInput);$("#update-settings-btn").on('click',function(){var input=$("#trade-url").val().trim();if(tradeURLInput.data("lastval")!=input){if(input.contains("token")){var token=input.substring(input.indexOf("token=")+ 6);if(token.length==8){doSend("trade_url"+ input);$("#trade-url").prop('disabled',true);}}}});$('#pv-submit').on('click',function(){var hash=$("#pv-hash").val();var secret=$("#pv-secret").val();var percent=$("#pv-percent").val();$("#pv-submit").prop("disabled","disabled");doSend("pvcheck~"+ hash+"~"+ secret+"~"+ percent);$("#pv-result").empty();pvSpinner=new Spinner().spin(document.getElementById("pv-popup"));setTimeout(function(){if($("#pv-result").is(':empty')){pvSpinner.stop();$("#pv-result").append("<p>An error occurred!</p>");}},10000);});var chatArrow=$("#chat_arrow");chatArrow.click(function(){var isCollapsed=chatArrow.hasClass('arrow_collapsed');collapseChat(!isCollapsed);document.cookie="chat_decol="+ isCollapsed;});var inventoryArrow=$("#inventory_arrow");inventoryArrow.click(function(){var isCollapsed=inventoryArrow.hasClass('arrow_collapsed');collapseInventory(!isCollapsed);document.cookie="inv_decol="+ isCollapsed;});var isChatDecollapsed="true"==getCookie("chat_decol");var isInventoryDecollapsed="true"==getCookie("inv_decol");if(isChatDecollapsed){collapseChat(false);}
if(isInventoryDecollapsed){collapseInventory(false);}});function collapseChat(shouldCollapse){var chatArrow=$("#chat_arrow");var isCollapsed=chatArrow.hasClass('arrow_collapsed');if(isCollapsed==shouldCollapse){return;}
chatArrow.toggleClass('arrow_collapsed');if(chatArrow.hasClass('arrow_right')){chatArrow.removeClass('arrow_right');chatArrow.addClass('arrow_left');}else{chatArrow.removeClass('arrow_left');chatArrow.addClass('arrow_right');}
if(shouldCollapse){$("#chatbox").show();$("#chatbox").animate({'width':'300px','min-width':'200px'},250,function(){resizeChat();});$(".log").animate({'margin-right':'302px'},250);}else{$("#chatbox").animate({'width':'0px','min-width':'0px'},250,function(){$("#chatbox").hide();resizeChat();});$(".log").animate({'margin-right':'2px'},250);}}
function collapseInventory(shouldCollapse){var invArrow=$("#inventory_arrow");var isCollapsed=invArrow.hasClass('arrow_collapsed');if(isCollapsed==shouldCollapse){return;}
invArrow.toggleClass('arrow_collapsed');if(invArrow.hasClass('arrow_right')){invArrow.removeClass('arrow_right');invArrow.addClass('arrow_left');}else{invArrow.removeClass('arrow_left');invArrow.addClass('arrow_right');}
var fullInvWidth=300;if(navigator.userAgent.indexOf("Firefox")!=-1){fullInvWidth=304;}
if(shouldCollapse){$("#inventory").show();$("#inventory").animate({'width':fullInvWidth+'px','min-width':'200px'},250);$(".various").animate({'left':fullInvWidth+'px'},250);$(".log").animate({'margin-left':(254+ fullInvWidth)+'px'},250);}else{$("#inventory").animate({'width':'0px','min-width':'0px'},250,function(){$("#inventory").hide();});$(".various").animate({'left':'0px'},250);$(".log").animate({'margin-left':'252px'},250);}}
var zoomLevel;function stopPVSpinner(){pvSpinner.stop();}
function openInNewTab(url){window.open(url,'_blank');}
function resizeApp(){var zoomLevelH=Math.max(650,$(window).height())/ 979;
var zoomLevelW=$(window).width()/ 1200;
zoomLevel=Math.max(0.55,Math.min(zoomLevelH,zoomLevelW));var vw=100/zoomLevel;var vh=100/zoomLevel;$('body').css({'width':vw+'vw','height':vh+'vh','zoom':zoomLevel,'-moz-transform':'scale('+ zoomLevel+')','-moz-transform-origin':'0 0'});}
$(window).load(resizeApp);$(window).resize(resizeApp);function getAssetURL(asset){return hostname+ assetPath+ asset;}
function onWithdrawRetry(withdrawId){doSend("retrywithdrawal~"+ withdrawId);}