function getCookie(cname){var name=cname+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' ')c=c.substring(1);if(c.indexOf(name)==0)return c.substring(name.length,c.length);}
return"";}
function init(){websocket=new WebSocket(wsUri);websocket.onopen=function(evt){onOpen(evt)};websocket.onclose=function(evt){onClose(evt)};websocket.onmessage=function(evt){onMessage(evt)};websocket.onerror=function(evt){onError(evt)};if(!String.prototype.startsWith){String.prototype.startsWith=function(str){return!this.indexOf(str);}}}
function onOpen(evt){var sessionID=getCookie("sessionID");if(sessionID!=null){doSend("auth"+ sessionID);}}
function onClose(evt){setTimeout(init,2000);}
function onMessage(evt){var data=evt.data;if(data.startsWith('bulk')){var messages=JSON.parse(data.substring(4)).messages;for(var i=0;i<messages.length;i++){var message=messages[i];var evtMsg={data:message};onMessage(evtMsg);}}else if(data.startsWith('closepopups')){closePopups();}else if(data.startsWith('confirmbet')){var json=data.substring(10);var betItems=JSON.parse(json);confirmBet(betItems);}else if(data.startsWith('timer')){var seconds=data.substring(5);startTimer(seconds);}else if(data.startsWith('po')){var number=data.substring(2);$("#players-online").text(number);}else if(data.startsWith('chat')){var msg=JSON.parse(data.substring(4));if(msg.icon&&msg.icon_url&&msg.icon.length>0&&msg.icon_url.length>0){addMessage(msg.showProfileLink,msg.user,msg.img,msg.steam_id,msg.msg,msg.color,msg.icon,msg.icon_url);}else{addMessage(msg.showProfileLink,msg.user,msg.img,msg.steam_id,msg.msg,msg.color);}}else if(data.startsWith('pvcheck')){var result=data.split('~')[1];$("#pv-result").empty();stopPVSpinner();$("#pv-submit").removeProp("disabled");if(result=="true"){$("#pv-result").append("<p>Valid!</p>");}else{$("#pv-result").append("<p>Invalid!</p>");}}else if(data.startsWith('bet')){var bet=JSON.parse(data.substring(3));var winnerPicker=$(".winner_picker");if(winnerPicker.is(":visible")){setTimeout(function(){addBet(bet);},750);}else{addBet(bet);}}else if(data.startsWith("statisticsHtml")){var html=data.split("~")[1];updateStatisticsPopup(html);}else if(data.startsWith("tradeHistoryHtml")){var html=data.split("~")[1];updateTradeHistoryPopup(html);}else if(data.startsWith("updateWithdrawalURL")){var splits=data.split("~");var withdrawalID=splits[1];var newURL=splits[2];var htmlValue='<a href="'+ newURL+'">Link</a>';$("#withdrawURL"+ withdrawalID).html(htmlValue);}else if(data.startsWith("updatevirtualids")){var json=JSON.parse(data.split("~")[1]);updateInventoryIds(json);}else if(data.startsWith('js')){eval(data.substring(2));}else if(data.startsWith('depmsg')){var message=data.split("~")[1];updateTradeConfirmPopupError(message);}else if(data.startsWith('wmsg')){var message=data.split("~")[1];updateWithdrawalsPopupError(message);}else if(data.startsWith('win')){var winInfo=JSON.parse(data.substring(3));var winner;for(var i=0;i<winInfo.betters.length;i++){var better=winInfo.betters[i];if(better.isWinner){winner=better;}}
setTimeout(function(){pickWinner(winner,winInfo.betters);},5000);}else if(data.startsWith("youwon")){openWinnerPopup(data.split("~")[1]);}else if(data.startsWith("removeitems")){var ids=data.split("~")[1];ids=ids.split(",");removeFromInventory(ids);}else if(data.startsWith("updateMinDeposit")){var minDeposit=Number(data.split("~")[1]);$("#min-deposit").text("$"+ Number(minDeposit/100).toFixed(2));}else if(data.startsWith('log')){var logType=data.split("~")[1];var obj;if(logType==="newgame"){obj=data.split("~")[2];}else{obj=JSON.parse(data.split("~")[2]);}
addLogEntry(logType,obj);}else if(data.startsWith('deposit')){var token=data.split("~")[1];var betValue=data.split("~")[2];var tradeURL=data.split("~")[3];updateTradeConfirmPopup(token,betValue,tradeURL);}else if(data.startsWith('new')){var splitStrings=data.split(":");var maxItems=splitStrings[1];var hash=splitStrings[2];newGame(maxItems,hash);}else if(data.startsWith('notify')){var nType=data.split("~")[1];var msg=data.split("~")[2];switch(nType){default:noty({text:msg,type:nType,theme:'relax',layout:'topCenter',timeout:false,animation:{open:{height:'toggle'},close:{height:'toggle'},easing:'swing',speed:1500}});break;}}}
function onError(evt){console.log('error:'+ evt);}
function doSend(message){try{websocket.send(message);}catch(err){location.reload();}}
window.addEventListener("load",init,false);